name: pokedex_franq
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase depedencies
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.0
  firebase_analytics: ^10.0.7
  firebase_crashlytics: ^3.0.7

  dio: ^4.0.6
  fpdart: ^0.3.0
  get_it: ^7.2.0
  equatable: ^2.0.5
  injectable: ^2.1.0
  auto_route: ^5.0.4
  flutter_bloc: ^8.1.1
  google_sign_in: ^5.4.2
  cupertino_icons: ^1.0.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^2.0.1
  build_runner: ^2.3.2
  flutter_flavorizr: ^2.1.5
  injectable_generator: ^2.1.3
  auto_route_generator: ^5.0.3

flutter:
  uses-material-design: true